name:                asteroid-detection-hs
version:             0.1.0.0
github:              "AnthonyMl/asteroid-detection-hs"
license:             BSD3
author:              "AnthonyMl"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/AnthonyMl/asteroid-detection-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  asteroid-detection-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asteroid-detection-hs

tests:
  asteroid-detection-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asteroid-detection-hs
