[package]
name = "intersection_detection"
version = "0.1.0"
authors = ["AnthonyMl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
